{{- if .Values.configFile.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "busybox.fullname" . }}-config
  labels:
    {{- include "busybox.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.configFile.fileName }}: {{ .Values.configFile.content | quote }}
{{- end }}
