apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "picoclaw.fullname" . }}
  labels:
    {{- include "picoclaw.labels" . | nindent 4 }}
data:
  BOT_TYPE: picoclaw
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
